// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tmp_kolos_02.Entities;

namespace tmp_kolos_02.Migrations
{
    [DbContext(typeof(FireContext))]
    [Migration("20220606155422_AddedCFTables")]
    partial class AddedCFTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tmp_kolos_02.Entities.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NeedSpecialEquipment")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction")
                        .HasName("Action_pk");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("tmp_kolos_02.Entities.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("SpecialEquipment")
                        .HasColumnType("tinyint");

                    b.HasKey("IdFireTruck")
                        .HasName("FireTruck_pk");

                    b.ToTable("FireTruck");
                });

            modelBuilder.Entity("tmp_kolos_02.Entities.FireTruckAction", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssigmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdFireTruck", "IdAction")
                        .HasName("FireTruckAction_pk");

                    b.HasIndex("IdAction");

                    b.ToTable("FireTruck_Action");
                });

            modelBuilder.Entity("tmp_kolos_02.Entities.FireTruckAction", b =>
                {
                    b.HasOne("tmp_kolos_02.Entities.Action", "IdActionNavigation")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdAction")
                        .HasConstraintName("FireTruckAction_Action")
                        .IsRequired();

                    b.HasOne("tmp_kolos_02.Entities.FireTruck", "IdFireTruckNavigation")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdFireTruck")
                        .HasConstraintName("FireTruckAction_FireTruck")
                        .IsRequired();

                    b.Navigation("IdActionNavigation");

                    b.Navigation("IdFireTruckNavigation");
                });

            modelBuilder.Entity("tmp_kolos_02.Entities.Action", b =>
                {
                    b.Navigation("FireTruckActions");
                });

            modelBuilder.Entity("tmp_kolos_02.Entities.FireTruck", b =>
                {
                    b.Navigation("FireTruckActions");
                });
#pragma warning restore 612, 618
        }
    }
}
